In [2]:
# Ruchika Bhat  25070123095
# Aim: Study of Pandas Library

In [57]:
# introduction to pandas
# pandas : panel data
# (used for structural data, EDA, data cleaning)

import pandas as pd

s = pd.Series([10,20,30,40])
print(s)

# create dataframe
data = {
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}

df = pd.DataFrame(data)
display(df)

# if you have to print first 5 rows use : df.head()
# if you have to print last 5 rows use : df.tail()


# find the structure of the DataFrame (how many rows and columns)
display(df.shape)

# find the dimensions (how many varibles/parameters are there)
display(df.ndim)

# find the size (how many elements are there)
display(df.size)

# display the column name
display(df.columns)

# check data types of each column
display(df.dtypes)

# access individual column
display(df["Name"])

# access specific row
display(df.loc[1])

# add a new column
(df["Grade"]) = ["First Class","Distinction","Second Class"]
display(df)

# update data in DataFrame
# (change marks of student A to 88.)
df.loc[0,"Marks"] = 81
display(df)

# delete a column
df1 = df.drop("Grade",axis=1)   # if we write axis = 0 it will delete the row and at 1 it delete column
display(df1)                    # here data didn't overwrite but if you want to overwrite data use implant=True
display(df)

# perform basic statistical analysis
mean=df["Marks"].mean()             # calculates mean
display(mean)

max=df["Marks"].max()               # calculates max
display(max)

min=df["Marks"].min()               # calculates min
display(min)

# apply condition (filtering)
# display stdents soring ore than 80.
df[df["Marks"] > 80]

0    10
1    20
2    30
3    40
dtype: int64

  Name  Marks
0    A     85
1    B     90
2    C     78

(3, 2)

2

6

Index(['Name', 'Marks'], dtype='object')

Name     object
Marks     int64
dtype: object

0    A
1    B
2    C
Name: Name, dtype: object

Name      B
Marks    90
Name: 1, dtype: object

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

  Name  Marks         Grade
0    A     81   First Class
1    B     90   Distinction
2    C     78  Second Class

  Name  Marks
0    A     81
1    B     90
2    C     78

  Name  Marks         Grade
0    A     81   First Class
1    B     90   Distinction
2    C     78  Second Class

np.float64(83.0)

90

78

  Name  Marks        Grade
0    A     81  First Class
1    B     90  Distinction